### ISSUE TITLE
Web > Chat Input doesn't clear on form submit

### ISSUE THREAD

**Issue by supernintendo** [liveview-native/elixirconf_chat#31]

**Comment by duggiefresh** [comment]
Example screenshot, on web client: 

![Screen Shot 2023-08-30 at 9 48 42 AM](https://github.com/liveview-native/elixirconf_chat/assets/1206678/78e292cb-e7fc-4314-9f0d-1944cd26f69d)

**Comment by duggiefresh** [comment]
Tested in Firefox and Brave: 

The input will clear as expected if I click on the purple "submit form button." The input will not clear when hitting _ENTER_ on the keyboard
