### ISSUE TITLE
iOS: App crashes during login flow

### ISSUE THREAD

**Issue by brzpegasus** [liveview-native/elixirconf_chat#57]
Tested on: iOS 16.6

I reinstalled the app after the latest fix that was meant to address the app crashing when moving from/to the background, and am unable to get past the login flow due to the app crashing when I come back to the app to enter the verification code. Steps to reproduce:

1. Open the app
1. Enter an email address to login
1. Move the app to the background to fetch the verification code
1. Return to the app
[App crashes]

See crash log: [ElixirConfChat-2023-08-31-195919](https://github.com/liveview-native/elixirconf_chat/files/12491805/ElixirConfChat-2023-08-31-195919.txt) (renamed from .ips to .txt for upload purposes).

**Comment by bcardarella** [comment]
I was able to reproduce on mobile

**Comment by bcardarella** [comment]
The app also crashed on macos when I tried login flow right now with v1(6).

**Comment by carson-katri** [comment]
Does it include this PR? https://github.com/liveview-native/liveview-client-swiftui/pull/1122

**Comment by brzpegasus** [comment]
🤔 That PR was merged 5 hrs ago, so maybe not? I am testing on the latest build. If we redeploy tomorrow morning, I can test again to verify.
