### ISSUE TITLE
Web - No option to know the attendee list in a room

### ISSUE THREAD

**Issue by swathimaanyam** [liveview-native/elixirconf_chat#69]
This maybe an _enhancement_. 

The attendees count is showing up when we visit the rooms but it is unclear about who's available in a room. It may be helpful if the attendees info is provided on mouse-over action of the room.
<img width="1728" alt="Screen Shot 2023-09-01 at 11 30 50 AM" src="https://github.com/liveview-native/elixirconf_chat/assets/58893057/18396483-ca29-4eac-ae8b-63a5d554c371">

**Comment by AZholtkevych** [comment]
Duplicates #46 . Rejecting
