### ISSUE TITLE
"Doors Open" always shows next to every time slot

### ISSUE THREAD

**Issue by brzpegasus** [liveview-native/elixirconf_chat#78]
I'm unclear what functionality is expected here (and couldn't find it in the design), but the text "Doors Open" shows next to every time slot and is hardcoded.

<img width="552" alt="Screenshot 2023-09-02 at 5 00 40 PM" src="https://github.com/liveview-native/elixirconf_chat/assets/1691398/b5935cd5-765c-4ac5-b293-d3245f828c84">

**Comment by brzpegasus** [comment]
My interpretation of the design is that "Doors Open" is not intended to be functional, and only appears within the registration reception time block. I'd also vote to simply remove it as the functionality is unclear, and doesn't seem necessary.

**Comment by pursuitofleisure** [comment]
Completed via PR #80
